yolo_model:

  config_file:
    name: yolov3.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.4
  detection_classes:
    names:
      - person
      - bicycle
      - car
      - motorbike
      - aeroplane
      - bus
      - train
      - truck
